functional:
 - Игроки должны видеть написание кода своего сопернника в реальном времени, без торможений
 - Игрок должен иметь возможность выбирать язык программирования для игры (C#, C++, python, rust, ruby, goland)
 - Игрок должен иметь возможность авторизироваться через Email
 - Игрок должен иметь возможность авторизироваться через Google
 - Игрок должен иметь возможность авторизироваться через Github
 - Игрок должен иметь возможность приглашать случайного игрока в игру
 - Игрок должен иметь возможность отклонять приглашение в игру
 - Игрок должен иметь возможность создавать свои турниры
 - Игрок должен иметь возможность изменять свой никнейм
 - Игрок должен иметь возможность изменять свой пароль
 - Время матча должно быть ограничего
non-functional:
 - Система должна выдержать нагрузку в 1000 пользователей
 - Интерфейс должен иметь русскую и английскую локализацию
 - Веб-сайт должен быть совместим с последними версиями браузеров (Google Chrome, Mazila, Safari)
 - Веб-сайт должен быть доступен на различных устройствах
 - Веб-сайт должен иметь мобильную версию
 - Сайт должен быть безопасным и защищать данные пользователя
implicit:
 - Веб-сайт должен работать на протоколе https
 - Игрок должен иметь возможность просматривать LEADERBOARD в развернутом ввиде в виде таблицы
 - Игрок должен иметь возможность настраивать звуковое сопровождения приглашения в игру
 - Игрок должен иметь возможность настраивать громкость звукового сопровождения
 - Игрок при создании матча должен иметь возможность выбрать ограничение по времени для своей игры
 - Минимальное время матча должно быть 3 минуты
 - Максиамльное время матча должно быть 60 минут
 - По истечению установлденног овремени, игра должна завершаться
 - Победитель игры выбирается по тому, кто верно решил задачу
 - Игрок должен иметь возможность присоединиться к игре в лобби
 - Игрок должен иметь возможность отправлять сообщения другим пользователям
 - Игрок должен иметь возможность менять сложность своей игры
 - Игрок должен иметь возможность играть с ботом
 - Игрок должен иметь возможность настраивать сложность бота
 - Игрок должен иметь возможность вернуться к покинутой игре
