functional:
 1 - Игроки должны видеть написание кода своего сопернника в реальном времени, без торможений
 2 - Игрок должен иметь возможность выбирать язык программирования для игры
 3 - Игрок должен иметь возможность авторизироваться через VK
 4 - Игрок должен иметь возможность авторизироваться через Email
 5 - Игрок должен иметь возможность авторизироваться через Google
 6 - Игрок должен иметь возможность авторизироваться через Github
 7 - Игрок должен иметь возможность приглашать случайного игрока в игру
 8 - Игрок должен иметь возможность отклонять приглашение в игру
 8 - Игрок должен иметь возможность создавать свои турниры
 10 - Игрок должен иметь возможность изменять свою персональную информацию
 11 - В игре должны быть предаставленны популярные языки программирования для выбора
 12 - Время матча должно быть ограничего
non-functional:
 1 - Система должна выдержать нагрузку в 1000 пользователей
 2 - Интерфейс должен иметь русскую и английскую локализацию
 3 - Веб-сайт должен быть совместим с последними версиями браузеров (Google Chrome, Mazila, Safari)
 4 - Веб-сайт должен быть доступен на различных устройствах
 5 - Веб-сайт должен иметь мобильную версию
 6 - Сайт должен быть безопасным и защищать данные пользователя
implicit:
 1 - Веб-сайт должен работать на протоколе https
 2 - Игрок должен иметь возможность просматривать LEADERBOARD в развернутом ввиде в виде таблицы
 3 - Игрок должен иметь возможность настраивать звуковое сопровождения приглашения в игру
 4 - Игрок должен иметь возможность настраивать громкость звукового сопровождения
 5 - Игрок при создании матча должен иметь возможность выбрать ограничение по времени для своей игры
 6 - Минимальное время матча должно быть 3 минуты
 7 - Максиамльное время матча должно быть 60 минут
 8 - По истечению установлденног овремени, игра должна завершаться
 9 - Победитель игры выбирается по тому, кто верно решил задачу
 10 - Игрок должен иметь возможность присоединиться к игре в лобби
 11 - Игрок должен иметь возможность отправлять сообщения другим пользователям
 12 - Игрок должен иметь возможность менять сложность своей игры
 13 - Игрок должен иметь возможность играть с ботом
 14 - Игрок должен иметь возможность настраивать сложность бота
 15 - Игрок должен иметь возможность вернуться к покинутой игре
